language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
after-success: 
 - cargo login $CARGO_TOKEN
 - cargo package 
 - cargo publish