language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success:
  - cargo publish --token $CARGO_TOKEN
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
