[package]
name = "httimple"
version = "0.1.0"
authors = ["Mona Lisa <halvor98@outlook.com>"]

[dependencies]
rustls = "*"
mio = "0.6"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
docopt = "0.8"
env_logger = "0.4.2"
webpki-roots = "0.14.0"
ct-logs = "0.3"
regex = "0.2"

