[package]
name = "httimple"
version = "0.1.0"
authors = ["Mona Lisa <halvor98@outlook.com>"]
exclude = [
    "main.rs",
]

[dependencies]

bitreader = "0.3.1"
mio = "0.6.14"
rustls = "0.12.0"
hpack_codec = "0.1.0"


