[package]
name = "httimple"
version = "0.1.6"
authors = ["Mona Lisa <halvor98@outlook.com>"]
exclude = [
    "src/main.rs",
]
description = "Simple HTTP2 package 😃 " 
license = "MIT"

[dependencies]

bitreader = "0.3.1"
mio = "0.6.14"
rustls = "0.12.0"
hpack_codec = "0.1.0"


